pipeline {
    agent any
    stages {
        stage("Test") {
            test()
        }
        stage("Build") {
            build()
        }
        stage("Publish") {
            publish()
        }
        stage("Deploy") {
            deploy()
        }
    }
}
